name: 'Upload Static Website to Azure Storage'
description: 'Uploads static website files to Azure Blob Storage hoho'
inputs:
  sourcePath:
    description: 'Path to static website files'
    required: false
    default: 'dist/apps/prypco'
  run_condition:
    description: 'Condition to run this action'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set deployment start time
      if: ${{ inputs.run_condition == 'true' }}
      shell: bash
      run: |
        echo "Setting deployment start time..."
        echo "deploy_start_time=$(date -u +%s)" >> $GITHUB_ENV
