name: Build react App

on:
  workflow_call:
    inputs:
      buildCommand:
        type: string
        default: "npm run build"
      app_name:
        type: string
        default: ""
      node_version:
        type: string
        default: "20.x"

jobs:
  build-ng-app:
    name: Build ${{ inputs.app_name }} App Test check
    runs-on: ubuntu-latest

    env:
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install Angular CLI and dependencies
        uses: anujrajkumar/template/.github/actions/custom@v0.0.29
