on: 
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release-on-push:
    if: |
      !contains(github.event.head_commit.message, 'renovate') &&
      !contains(github.actor, 'renovate[bot]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.tag.outputs.new_tag }}
          tag_name: ${{ steps.tag.outputs.new_tag }}
          generate_release_notes: true
